aplicativo/DesignCal/urls.py
from django.urls import path
from . import views

app_name = "DesignCal"

urlpatterns = [
    #_____________________________________________________
    #Index
    path('', views.index, name='index'),
    #_____________________________________________________
    #Login
    path('loginFormulario/', views.loginFormulario, name='login-formulario'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    #_____________________________________________________
    #Patrones
    path('Patrones/', views.listarPatron, name='patron'),
    path('Patron-add/', views.insertarPatron, name='patron-add'),
    path('Patron-guardar/', views.guardarPatron, name='patron-guardar'),
    path('Patron-eliminar/<int:id>', views.eliminarPatron, name='patron-eliminar'),
    path('Patron-editar/<int:id>', views.editarPatron, name="patron-editar"),
    path('Patron-actualizar/', views.actualizarPatron, name="patron-actualizar"),
    path('Patron-buscar/', views.buscarPatron, name="patron-buscar"),
    path('Patrones-tarjetas/', views.tarjetasPatrones, name='patrones'),
    #_____________________________________________________
    #Usuarios
    path('usuario/', views.listarUsuarios, name='usuario'),
    path('usuario-add/', views.agregarUsuarios, name='usuario-add'),
    path('usuario-guardar/', views.guardarUsuario, name='usuario-guardar'),
    path('usuario-eliminar/<int:cedula>', views.eliminarUsuario, name='usuario-eliminar'),
    path('usuario-editar/<int:cedula>', views.editarUsuario, name='usuario-editar'),
    path('usuario-actualizar/', views.actualizarUsuario, name='usuario-actualizar'),
    path('usuario-buscar/', views.buscarUsuario, name='usuario-buscar'),
    path('perfil/', views.perfil, name='usuario-perfil'),
    path('actualizarPerfil/', views.actualizarPerfil, name='usuario-actualizarPerfil'),
    #______________________________________________________________________________________
    #Roles
    path('roles/', views.listarRoles, name='roles'),
    path('rol-add/', views.crearRol, name='rol-add'),
    path('rol-guardar/', views.guardarRol, name='rol-guardar'),
    path('rol-eliminar/<int:id>', views.eliminarRol, name='rol-eliminar'),
    path('rol-editar/<int:id>', views.editarRol, name='rol-editar'),
    path('rol-actualizar/', views.actualizarRol, name='rol-actualizar'),
    path('rol-buscar/', views.buscarRol, name='rol-buscar'),
    #______________________________________________________________________________________
    #Facturas
    path('facturas/', views.listarFacturas, name='facturas'),
    path('facturas-add/', views.agregarFactura, name='facturas-add'),
    path('facturas-guardar/', views.guardarFactura, name='facturas-guardar'),
    path('facturas-buscar/', views.buscarFactura, name='facturas-buscar'),
    #______________________________________________________________________________________
    #Tipo_Patrón
    path('tipoPatron/', views.listartipoPatron, name='tipoPatron'),
    path('tipoPatron-add/', views.creartipoPatron, name='tipoPatron-add'),
    path('tipoPatron-guardar/', views.guardartipoPatron, name='tipoPatron-guardar'),
    path('tipoPatron-eliminar/<int:id>', views.eliminartipoPatron, name='tipoPatron-eliminar'),
    path('tipoPatron-editar/<int:id>', views.editartipoPatron, name='tipoPatron-editar'),
    path('tipoPatron-actualizar/', views.actualizartipoPatron, name='tipoPatron-actualizar'),
    path('tipoPatron-buscar/', views.buscartipoPatron, name='tipoPatron-buscar'),
    #______________________________________________________________________________________________
    #Compras
    path('compras/', views.listarCompras, name='compras'),
    path('compras-add/', views.insertarCompra, name='compra-add'),
    path('compras-guardar/', views.guardarCompra, name='compra-guardar'),
    path('compras-editar/<int:id>', views.editarCompra, name='compra-editar'),
    path('compras-actualizar/', views.actualizarCompra, name='compra-actualizar'),
    path('compras-buscar/', views.buscarCompra, name='compra-buscar'),
    #______________________________________________________________________________________________
    #Correos
    path('correos/', views.listarCorreos, name='correos'),
    path('correos-add/', views.crearCorreo, name='correos-add'),
    path('correos-guardar/', views.guardarCorreo, name='correos-guardar' ),
    path('correos-editar/<int:id>', views.editarCorreo, name='correos-editar'),
    path('correos-actualizar/', views.actualizarCorreo, name='correos-actualizar'),
    path('correos-buscar/', views.buscarCorreos, name='correos-buscar'),
    path('correos-eliminar/<int:id>', views.eliminarCorreo, name='correos-eliminar'),
]

aplicativo/aplicativo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DesignCal.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

aplicativo/DesignCal/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models

class Rol(models.Model):
    NombreRol = models.CharField( max_length=20, default="Cliente")
    def __str__(self):
        return self.NombreRol

class Usuario(models.Model):
    cedula = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=254)
    apellido = models.CharField(max_length=254)
    correo = models.EmailField(max_length=254, unique=True)
    usuario = models.CharField(max_length=20, unique=True)
    contrasena = models.CharField(max_length=10)
    NombreRol = models.ForeignKey(Rol, on_delete= models.DO_NOTHING)
    fotoPerfil = models.ImageField(upload_to = 'DesignCal/fotosPerfil', default= 'DesignCal/fotosPerfil/default.jpg')
    def __str__(self): 
       return self.nombre

class TipoPatron(models.Model):
    tipoPatron = models.CharField(max_length=254)
    descripcion = models.TextField(default='Pendiente')
    def __str__(self):
        return self.tipoPatron

class Patrone(models.Model):
    nombreArchivo = models.CharField(max_length=200)
    descripcion = models.TextField(default='Pendiente')
    precio = models.BigIntegerField(default=0)
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    tipoPatron = models.ForeignKey(TipoPatron, on_delete= models.DO_NOTHING)
    archivo = models.FileField(upload_to = 'DesignCal/files', default= None)
    imagen = models.ImageField(upload_to = 'DesignCal/fotos', default = 'DesignCal/fotos/default.jpg')
    
    def __str__(self):
        return self.nombreArchivo

class Factura(models.Model):
    nombreArchivo = models.ForeignKey(Patrone, on_delete= models.DO_NOTHING)
    cantidad = models.SmallIntegerField(default=0)
    total = models.BigIntegerField(default=0)
    fecha = models.DateTimeField()
    def __str__(self):
        return str(self.pk)

class Compra(models.Model):
    IdFactura = models.ForeignKey(Factura, on_delete= models.DO_NOTHING, default= 0)
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    descripcion = models.CharField(max_length=250, default='Pendiente')
    estados = (
        ("P", "Pendiente"),
        ("CP", "Completo"),
        ("C", "Cancelado"),
    )
    estado = models.CharField(choices=estados, max_length=2, default="P")
    def __str__(self):
        return str(self.pk)

class Correos(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    titulo = models.CharField(max_length=250, unique=True)
    contenido = models.CharField(max_length=254)
    def __str__(self):
        return str(self.titulo)


aplicativo/DesignCal/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from .models import Factura, Patrone, Rol, TipoPatron, Usuario, Compra, Correos
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from os import remove, path 
BASE_DIR = Path(__file__).resolve().parent.parent
#cifrado de claves
from .crypt import claveEncriptada
#----------------------------------------------------------
#Index
def index(request):
    return render(request, 'DesignCal/index.html')
#----------------------------------------------------------
#Login
def loginFormulario(request):
    return render(request, 'DesignCal/Login/login.html')

def login(request):
    #Capturamos los datos enviados
    if request.method == "POST":
        try:
            u = request.POST["usuario"]
            p = claveEncriptada(request.POST["contrasena"])
            print(p)
            
            #Verificar si existe en la base de datos
            q = Usuario.objects.get(usuario = u, contrasena = p)
            
            #Crear la variable de sesión, aquí interesa guardar quién está logueado, para controlar los permisos
            request.session["logueo"] = [q.cedula, q.nombre, q.apellido, q.NombreRol.NombreRol]
            return redirect('DesignCal:index')
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario no existe")
            return redirect('DesignCal:login-formulario')
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('DesignCal:login-formulario')
        
def logout(request):
    try:
        del request.session["logueo"]
        messages.success(request, "Sesión cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Ocurrió un error: {e}")
    return redirect('DesignCal:index')

def perfil(request):
    login = request.session.get('logueo', False)
    q = Usuario.objects.get(pk = login[0])
    contexto = {'perfil': q}
    return render(request, 'DesignCal/Usuarios/perfil.html', contexto)

def actualizarPerfil(request):
    
    if request.method == "POST":
        try:
            login = request.session.get('logueo', False)
            q = Usuario.objects.get(pk = login[0])
            q.nombre = request.POST['nombre']
            q.apellido = request.POST['apellido']
            
            #Control de correo
            if q.correo != request.POST["correo"]:
                try:
                    Usuario.objects.get(correo = request.POST["correo"])
                    raise Exception("Correo ya existe...")
                except Usuario.DoesNotExist:
                    messages.debug(request, "resultado consulta correo: OK")
                    q.correo = request.POST["correo"]
            else:
                q.correo = request.POST["correo"]
            
            #Control de usuario
            if q.usuario != request.POST["usuario"]:
                try:
                    Usuario.objects.get(usuario = request.POST["usuario"])
                    raise Exception("Usuario ya existe...")
                except Usuario.DoesNotExist:
                    messages.debug(request, "resultado consulta usuario: OK")
                    q.usuario = request.POST["usuario"]
            else:
                messages.debug(request, "No hay cambios en el usuario")
                q.usuario = request.POST["usuario"]
            
            if request.POST["contrasena"] != "":   
                q.contrasena = claveEncriptada(request.POST['contrasena'])
            
            q.save()
            #Enviar Correo
            #protocolo de correos electrónicos SMTP save mail transfer protocol.
            from django.core.mail import send_mail
            try:
                send_mail(
                    'Correo de prueba',
                    'Hola, te escribo desde DesignCal para probar el envío de mensajes desde mi projecto formativo en Django',
                    'valeriaye2019@gmail.com',
                    ['valeria1999.40@hotmail.com', 'vbustamante8@misena.edu.co', 'ruizt_3@hotmail.com'],
                    fail_silently=False
                )
                messages.info(request, "Correo enviado")
            except Exception as e:
                messages.error(request, f"Error: {e}")
            login[1] = q.nombre
            login[2] = q.apellido
            request.session["logueo"] = login
            
            messages.success(request, "Perfil actualizado correctamente.")
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario no existe")
        except Exception as e:
            messages.error(request, f"error: {e}")
    else:
        messages.warning(request, "Usted no envió datos.")
    
    return redirect('DesignCal:usuario-perfil')

#----------------------------------------------------------
#Patrones
def listarPatron(request):
    q = Patrone.objects.all()
    pag = Paginator(q, 5)
    page_number = request.GET.get('page')
    q = pag.get_page(page_number)
    contexto = {'datos': q}
    return render(request, 'DesignCal/Patrones/listarPatrones.html', contexto)

def tarjetasPatrones(request):
    q = Patrone.objects.all()
    contexto = {'datos': q}
    return render(request, 'DesignCal/Patrones/tarjetasPatrones.html', contexto)

def insertarPatron(request):
    t = TipoPatron.objects.all()
    a = Usuario.objects.all()
    contexto = {'usuario': a, 'tipoPatron': t}
    return render(request, 'DesignCal/Patrones/cargarPatrones.html', contexto)

def guardarPatron(request):
    try:
        if request.method == "POST":
            if request.FILES:
                fss = FileSystemStorage()
                a = request.FILES["archivo"]
                archivo = fss.save("DesignCal/files/" + a.name, a)
                f = request.FILES["imagen"]
                file = fss.save("DesignCal/fotos/" + f.name, f)
            
            else:
                file = "DesignCal/fotos/default.jpg"

            t = TipoPatron.objects.get(pk = request.POST["tipoPatron"])
            u = Usuario.objects.get(pk = request.POST["usuario"])
            p = Patrone(
                nombreArchivo = request.POST["nombreArchivo"],
                descripcion = request.POST["descripcion"],
                precio = request.POST["precio"],
                archivo = archivo,
                imagen = file,
                usuario = u,
                tipoPatron = t,
            )
            p.save()
            messages.success(request, "Nuevo patrón de moldería agregado")
            return redirect('DesignCal:patron')
        else:
            messages.warning(request, "Usted no envió datos")
            return redirect('DesignCal:patron')
    except Exception as e:
        messages.error(request, 'Error: ' + str(e))
        return redirect('DesignCal:patron')

def editarPatron(request, id):
    t = TipoPatron.objects.all()
    u = Usuario.objects.all()
    p = Patrone.objects.get(pk = id)
    contexto = {'datos': p, 'usuario': u, 'tipoPatron': t}
    return render(request, 'DesignCal/Patrones/editarPatrones.html', contexto)

def actualizarPatron(request):
    try:
        if request.method == "POST":
            t = TipoPatron.objects.get(pk = request.POST["tipoPatron"])
            u = Usuario.objects.get(pk = request.POST["usuario"])
            p = Patrone.objects.get(pk = request.POST["id"])
           
            if request.FILES:
                ruta_foto = str(BASE_DIR) + str(p.imagen.url)

                if path.exists(ruta_foto):
                    if p.imagen.url != "/uploads/DesignCal/fotos/default.jpg":
                        remove(ruta_foto)
                else:
                    raise Exception("La imagen no existe o no se encuentra")
                
                fss = FileSystemStorage()
                a = request.FILES["archivo"]
                archivo = fss.save("DesignCal/files/" + a.name, a)
                f = request.FILES["imagen"]
                file = fss.save("DesignCal/fotos/" + f.name, f)

                p.imagen = file
                p.archivo = archivo
            else:
                print("No se seleccionó foto nueva para éste patrón.")

            p.nombreArchivo = request.POST["nombreArchivo"]
            p.descripcion = request.POST["descripcion"]
            p.precio = request.POST["precio"]
            p.usuario = u
            p.tipoPatron = t

            p.save()
            messages.success(request, "Usuario actualizado con éxito")
            return redirect('DesignCal:patron')
        else:
            messages.warning(request, "No hay cambios")
            return redirect('DesignCal:patron')
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('DesignCal:patron')

def buscarPatron(request):
    if request.method == "POST":
        q = Patrone.objects.filter(Q(nombreArchivo__icontains = request.POST["dato"]) |
                                   Q(descripcion__icontains = request.POST["dato"]) |
                                   Q(precio__icontains = request.POST["dato"]) |
                                   Q(usuario__usuario__icontains = request.POST["dato"]) |
                                   Q(tipoPatron__icontains = request.POST["dato"]))
        pag = Paginator(q, 5)
        page_number = request.GET.get('page')
        q = pag.get_page(page_number)
        contexto = {'datos': q, 'datoBuscado': request.POST["dato"]}
        return render(request, 'DesignCal/Patrones/listarPatronesAjax.html', contexto)
    else:
        messages.warning(request, "Usted no envió datos...")

aplicativo/DesignCal/templates/DesignCal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Design-Cal</title>
    <link rel="stylesheet" href="{% static 'DesignCal/bootstrap-icons-1.9.1/bootstrap-icons.css' %}">
    
    <link rel="stylesheet" href="{% static 'DesignCal/css/DesignCal.css' %}">
    <link rel="stylesheet" href="{% static 'DesignCal/css/bootstrap.min.css' %}">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'DesignCal/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'DesignCal/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'DesignCal/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'DesignCal/favicon/site.webmanifest' %}">
</head>

<body>
    <header>
        <div id="banner">
            <a class="navbar-brand" id="logo" href="{% url 'DesignCal:index' %}">
                <img class="logo" src="{% static 'DesignCal/img/logo.jpg' %}" alt="logo">
            </a>
            <nav class="navbar navbar-expand-lg " id="navbar">
                
                <div class="collapse navbar-collapse" id="menu">
                    <div class="barra">
                        <ul class="navbar-nav mr-auto" id="nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'DesignCal:index' %}">Inicio <span
                                        class="sr-only"></span></a>
                            </li>
                            {% if request.session.logueo.3 == "Diseñador" or request.session.logueo.3 == "Administrador" %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Patrones
                                </a>
                                <ul class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:patron-add' %}">Cargar</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:patron' %}">Listar</a>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Tipos de patrones
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:tipoPatron' %}">Listar tipos de
                                        patrones</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:tipoPatron-add' %}">Agregar tipos
                                        de patrones</a>
                                </div>
                            </li>
                            {% endif %}
                            {% if request.session.logueo.3 == "Administrador" %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Usuarios
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:usuario-add' %}">Ingresar</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:usuario' %}">Listar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Roles
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:rol-add' %}">Ingresar</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:roles' %}">Listar</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Correos
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:correos-add' %}">Crear</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:correos' %}">Listar</a>
                                </div>

                            </li>
                            <li class="nav-item dropdown">

                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Compras
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:compra-add' %}">Agregar Compra</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:compras' %}">Listar Compras</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" href="#">
                                    Facturas
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'DesignCal:facturas-add' %}">Ingresar</a>
                                    <a class="dropdown-item" href="{% url 'DesignCal:facturas' %}">Listar</a>
                                </div>
                            </li>
                            {% endif %}
                            <li class="nav-item dropdown">
                                <a class="nav-link active" href="{% url 'DesignCal:patrones' %}">
                                    Patrones
                                </a>
                            </li>

                        </ul>
                    </div>
                    <div class="sesion">
                        <span class="d-flex">
                            {% if request.session.logueo %}
                            <!--Aquí verifica si existe el logueo-->
                            <button onclick="location.href='{% url 'DesignCal:usuario-perfil' %}';" class="btn btn-secundary"><i class="bi bi-person-circle"></i>{{ request.session.logueo.1 }}</button> 
                            <!--De esta manera sin especificar la posición, me muestra todo el vector-->

                            <a class="nav-link active" aria-current="page" href="{% url 'DesignCal:logout' %}"><i class="bi bi-box-arrow-right"></i></a>
                            {% else %}
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'DesignCal:login-formulario' %}">Iniciar Sesión</a>
                            <a class="nav-link" aria-current="page" href="{% url 'DesignCal:usuario-add' %}">Registrarse</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <main>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% elif message.tags == 'error' %}danger{% endif %}"
            role="alert">{{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <div class="contacto">
            <p id="contactanos">Contáctanos</p>
            <p>vbustamante8@misena.edu.co</p>
            <p>WhatsApp: +573014247110</p>
        </div>
        <div class="redes">
            <p>Nuestras Redes Sociales</p>

        </div>
    </footer>
    <script src="{% static 'DesignCal/js/jquery-3.6.1.min.js' %}"></script>
    <script src="{% static 'DesignCal/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'DesignCal/js/funciones.js' %}"></script>
</body>

</html>

aplicativo/DesignCal/templates/DesignCal/index.html
{% extends "DesignCal/base.html" %}
{% load static %}

{% block body %}
<div class="sobreNosotros">
    <div id="title">
        <p>
            Design-Cal
        </p>
        <h4>Venta de patrones de moda</h4>
    </div>
</div>
<div class="mainIndex">
    <div id="descripcion">
        <h4>Acerca de nosotros</h4>
        <p>Somos una empresa encargada de dar a conocer excelentes profesionales de patonaje y diseño de modas,
            facilitando la venta de sus patrones de diseño con un precio muy accesible y sin salir de tu casa.</p>
    </div>
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3"
                aria-label="Slide 4"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'DesignCal/img/inicio/bebeinicio.png' %}" class="d-block" alt="...">
                <div class="carousel-caption d-none d-md-block letra">
                    <h5>Encuentra ropa para tu bebé</h5>
                    <p>Descarga y haz tu misma la ropa para tu bebé.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5000">
                <img src="{% static 'DesignCal/img/inicio/ninosinicio.png' %}" class="d-block" alt="...">
                <div class="carousel-caption d-none d-md-block letra">
                    <h5>Encuentra ropa para los niños</h5>
                    <p>Descarga y crea divertidos outfits para los pequeños de la casa.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5000">
                <img src="{% static 'DesignCal/img/inicio/mujerinicio.png' %}" class="d-block" alt="...">
                <div class="carousel-caption d-none d-md-block letra">
                    <h5>Encuentra ropa para mujer</h5>
                    <p>Descarga, crea y combina dististos estilos para demostrar tu poder.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5000">
                <img src="{% static 'DesignCal/img/inicio/hombreinicio.png' %}" class="d-block" alt="...">
                <div class="carousel-caption d-none d-md-block letra">
                    <h5>Encuentra ropa para hombre</h5>
                    <p>Hermosos patrones para combinar y sacar a deslumbrar tu estilo.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

{% endblock %}