aplicativo/DesignCal/urls.py
from django.urls import path
from . import views

app_name = "DesignCal"

urlpatterns = [
    #_____________________________________________________
    #Index
    path('', views.index, name='index'),
    #_____________________________________________________
    #Login
    path('loginFormulario/', views.loginFormulario, name='login-formulario'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    #_____________________________________________________
    #Patrones
    path('Patrones/', views.listarPatron, name='patron'),
    path('Patron-add/', views.insertarPatron, name='patron-add'),
    path('Patron-guardar/', views.guardarPatron, name='patron-guardar'),
    path('Patron-eliminar/<int:id>', views.eliminarPatron, name='patron-eliminar'),
    path('Patron-editar/<int:id>', views.editarPatron, name="patron-editar"),
    path('Patron-actualizar/', views.actualizarPatron, name="patron-actualizar"),
    path('Patron-buscar/', views.buscarPatron, name="patron-buscar"),
    path('Patrones-tarjetas/', views.tarjetasPatrones, name='patrones'),
    #_____________________________________________________
    #Usuarios
    path('usuario/', views.listarUsuarios, name='usuario'),
    path('usuario-add/', views.agregarUsuarios, name='usuario-add'),
    path('usuario-guardar/', views.guardarUsuario, name='usuario-guardar'),
    path('usuario-eliminar/<int:cedula>', views.eliminarUsuario, name='usuario-eliminar'),
    path('usuario-editar/<int:cedula>', views.editarUsuario, name='usuario-editar'),
    path('usuario-actualizar/', views.actualizarUsuario, name='usuario-actualizar'),
    path('usuario-buscar/', views.buscarUsuario, name='usuario-buscar'),
    path('perfil/', views.perfil, name='usuario-perfil'),
    path('actualizarPerfil/', views.actualizarPerfil, name='usuario-actualizarPerfil'),
    #______________________________________________________________________________________
    #Roles
    path('roles/', views.listarRoles, name='roles'),
    path('rol-add/', views.crearRol, name='rol-add'),
    path('rol-guardar/', views.guardarRol, name='rol-guardar'),
    path('rol-eliminar/<int:id>', views.eliminarRol, name='rol-eliminar'),
    path('rol-editar/<int:id>', views.editarRol, name='rol-editar'),
    path('rol-actualizar/', views.actualizarRol, name='rol-actualizar'),
    path('rol-buscar/', views.buscarRol, name='rol-buscar'),
    #______________________________________________________________________________________
    #Facturas
    path('facturas/', views.listarFacturas, name='facturas'),
    path('facturas-add/', views.agregarFactura, name='facturas-add'),
    path('facturas-guardar/', views.guardarFactura, name='facturas-guardar'),
    path('facturas-buscar/', views.buscarFactura, name='facturas-buscar'),
    #______________________________________________________________________________________
    #Tipo_Patrón
    path('tipoPatron/', views.listartipoPatron, name='tipoPatron'),
    path('tipoPatron-add/', views.creartipoPatron, name='tipoPatron-add'),
    path('tipoPatron-guardar/', views.guardartipoPatron, name='tipoPatron-guardar'),
    path('tipoPatron-eliminar/<int:id>', views.eliminartipoPatron, name='tipoPatron-eliminar'),
    path('tipoPatron-editar/<int:id>', views.editartipoPatron, name='tipoPatron-editar'),
    path('tipoPatron-actualizar/', views.actualizartipoPatron, name='tipoPatron-actualizar'),
    path('tipoPatron-buscar/', views.buscartipoPatron, name='tipoPatron-buscar'),
    #______________________________________________________________________________________________
    #Compras
    path('compras/', views.listarCompras, name='compras'),
    path('compras-add/', views.insertarCompra, name='compra-add'),
    path('compras-guardar/', views.guardarCompra, name='compra-guardar'),
    path('compras-editar/<int:id>', views.editarCompra, name='compra-editar'),
    path('compras-actualizar/', views.actualizarCompra, name='compra-actualizar'),
    path('compras-buscar/', views.buscarCompra, name='compra-buscar'),
    #______________________________________________________________________________________________
    #Correos
    path('correos/', views.listarCorreos, name='correos'),
    path('correos-add/', views.crearCorreo, name='correos-add'),
    path('correos-guardar/', views.guardarCorreo, name='correos-guardar' ),
    path('correos-editar/<int:id>', views.editarCorreo, name='correos-editar'),
    path('correos-actualizar/', views.actualizarCorreo, name='correos-actualizar'),
    path('correos-buscar/', views.buscarCorreos, name='correos-buscar'),
    path('correos-eliminar/<int:id>', views.eliminarCorreo, name='correos-eliminar'),
]

aplicativo/aplicativo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DesignCal.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

aplicativo/DesignCal/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models

class Rol(models.Model):
    NombreRol = models.CharField( max_length=20, default="Cliente")
    def __str__(self):
        return self.NombreRol

class Usuario(models.Model):
    cedula = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=254)
    apellido = models.CharField(max_length=254)
    correo = models.EmailField(max_length=254, unique=True)
    usuario = models.CharField(max_length=20, unique=True)
    contrasena = models.CharField(max_length=10)
    NombreRol = models.ForeignKey(Rol, on_delete= models.DO_NOTHING)
    fotoPerfil = models.ImageField(upload_to = 'DesignCal/fotosPerfil', default= 'DesignCal/fotosPerfil/default.jpg')
    def __str__(self): 
       return self.nombre

class TipoPatron(models.Model):
    tipoPatron = models.CharField(max_length=254)
    descripcion = models.TextField(default='Pendiente')
    def __str__(self):
        return self.tipoPatron

class Patrone(models.Model):
    nombreArchivo = models.CharField(max_length=200)
    descripcion = models.TextField(default='Pendiente')
    precio = models.BigIntegerField(default=0)
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    tipoPatron = models.ForeignKey(TipoPatron, on_delete= models.DO_NOTHING)
    archivo = models.FileField(upload_to = 'DesignCal/files', default= None)
    imagen = models.ImageField(upload_to = 'DesignCal/fotos', default = 'DesignCal/fotos/default.jpg')
    
    def __str__(self):
        return self.nombreArchivo

class Factura(models.Model):
    nombreArchivo = models.ForeignKey(Patrone, on_delete= models.DO_NOTHING)
    cantidad = models.SmallIntegerField(default=0)
    total = models.BigIntegerField(default=0)
    fecha = models.DateTimeField()
    def __str__(self):
        return str(self.pk)

class Compra(models.Model):
    IdFactura = models.ForeignKey(Factura, on_delete= models.DO_NOTHING, default= 0)
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    descripcion = models.CharField(max_length=250, default='Pendiente')
    estados = (
        ("P", "Pendiente"),
        ("CP", "Completo"),
        ("C", "Cancelado"),
    )
    estado = models.CharField(choices=estados, max_length=2, default="P")
    def __str__(self):
        return str(self.pk)

class Correos(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete= models.DO_NOTHING)
    titulo = models.CharField(max_length=250, unique=True)
    contenido = models.CharField(max_length=254)
    def __str__(self):
        return str(self.titulo)


aplicativo/DesignCal/views.py
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from .models import Factura, Patrone, Rol, TipoPatron, Usuario, Compra, Correos
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from os import remove, path 
BASE_DIR = Path(__file__).resolve().parent.parent
#cifrado de claves
from .crypt import claveEncriptada
#----------------------------------------------------------
#Index
def index(request):
    return render(request, 'DesignCal/index.html')
#----------------------------------------------------------
#Login
def loginFormulario(request):
    return render(request, 'DesignCal/Login/login.html')

def login(request):
    #Capturamos los datos enviados
    if request.method == "POST":
        try:
            u = request.POST["usuario"]
            p = claveEncriptada(request.POST["contrasena"])
            print(p)
            
            #Verificar si existe en la base de datos
            q = Usuario.objects.get(usuario = u, contrasena = p)
            
            #Crear la variable de sesión, aquí interesa guardar quién está logueado, para controlar los permisos
            request.session["logueo"] = [q.cedula, q.nombre, q.apellido, q.NombreRol.NombreRol]
            return redirect('DesignCal:index')
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario no existe")
            return redirect('DesignCal:login-formulario')
    else:
        messages.warning(request, "Usted no envió datos...")
        return redirect('DesignCal:login-formulario')
        
def logout(request):
    try:
        del request.session["logueo"]
        messages.success(request, "Sesión cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Ocurrió un error: {e}")
    return redirect('DesignCal:index')

def perfil(request):
    login = request.session.get('logueo', False)
    q = Usuario.objects.get(pk = login[0])
    contexto = {'perfil': q}
    return render(request, 'DesignCal/Usuarios/perfil.html', contexto)

def actualizarPerfil(request):
    
    if request.method == "POST":
        try:
            login = request.session.get('logueo', False)
            q = Usuario.objects.get(pk = login[0])
            q.nombre = request.POST['nombre']
            q.apellido = request.POST['apellido']
            
            #Control de correo
            if q.correo != request.POST["correo"]:
                try:
                    Usuario.objects.get(correo = request.POST["correo"])
                    raise Exception("Correo ya existe...")
                except Usuario.DoesNotExist:
                    messages.debug(request, "resultado consulta correo: OK")
                    q.correo = request.POST["correo"]
            else:
                q.correo = request.POST["correo"]
            
            #Control de usuario
            if q.usuario != request.POST["usuario"]:
                try:
                    Usuario.objects.get(usuario = request.POST["usuario"])
                    raise Exception("Usuario ya existe...")
                except Usuario.DoesNotExist:
                    messages.debug(request, "resultado consulta usuario: OK")
                    q.usuario = request.POST["usuario"]
            else:
                messages.debug(request, "No hay cambios en el usuario")
                q.usuario = request.POST["usuario"]
            
            if request.POST["contrasena"] != "":   
                q.contrasena = claveEncriptada(request.POST['contrasena'])
            
            q.save()
            #Enviar Correo
            #protocolo de correos electrónicos SMTP save mail transfer protocol.
            from django.core.mail import send_mail
            try:
                send_mail(
                    'Correo de prueba',
                    'Hola, te escribo desde DesignCal para probar el envío de mensajes desde mi projecto formativo en Django',
                    'valeriaye2019@gmail.com',
                    ['valeria1999.40@hotmail.com', 'vbustamante8@misena.edu.co', 'ruizt_3@hotmail.com'],
                    fail_silently=False
                )
                messages.info(request, "Correo enviado")
            except Exception as e:
                messages.error(request, f"Error: {e}")
            login[1] = q.nombre
            login[2] = q.apellido
            request.session["logueo"] = login
            
            messages.success(request, "Perfil actualizado correctamente.")
        except Usuario.DoesNotExist:
            messages.error(request, "Usuario no existe")
        except Exception as e:
            messages.error(request, f"error: {e}")
    else:
        messages.warning(request, "Usted no envió datos.")
    
    return redirect('DesignCal:usuario-perfil')

#----------------------------------------------------------
#Patrones
def listarPatron(request):
    q = Patrone.objects.all()
    pag = Paginator(q, 5)
    page_number = request.GET.get('page')
    q = pag.get_page(page_number)
    contexto = {'datos': q}
    return render(request, 'DesignCal/Patrones/listarPatrones.html', contexto)

def tarjetasPatrones(request):
    q = Patrone.objects.all()
    contexto = {'datos': q}
    return render(request, 'DesignCal/Patrones/tarjetasPatrones.html', contexto)

def insertarPatron(request):
    t = TipoPatron.objects.all()
    a = Usuario.objects.all()
    contexto = {'usuario': a, 'tipoPatron': t}
    return render(request, 'DesignCal/Patrones/cargarPatrones.html', contexto)

def guardarPatron(request):
    try:
        if request.method == "POST":
            if request.FILES:
                fss = FileSystemStorage()
                a = request.FILES["archivo"]
                archivo = fss.save("DesignCal/files/" + a.name, a)
                f = request.FILES["imagen"]
                file = fss.save("DesignCal/fotos/" + f.name, f)
            
            else:
                file = "DesignCal/fotos/default.jpg"

            t = TipoPatron.objects.get(pk = request.POST["tipoPatron"])
            u = Usuario.objects.get(pk = request.POST["usuario"])
            p = Patrone(
                nombreArchivo = request.POST["nombreArchivo"],
                descripcion = request.POST["descripcion"],
                precio = request.POST["precio"],
                archivo = archivo,
                imagen = file,
                usuario = u,
                tipoPatron = t,
            )
            p.save()
            messages.success(request, "Nuevo patrón de moldería agregado")
            return redirect('DesignCal:patron')
        else:
            messages.warning(request, "Usted no envió datos")
            return redirect('DesignCal:patron')
    except Exception as e:
        messages.error(request, 'Error: ' + str(e))
        return redirect('DesignCal:patron')

def editarPatron(request, id):
    t = TipoPatron.objects.all()
    u = Usuario.objects.all()
    p = Patrone.objects.get(pk = id)
    contexto = {'datos': p, 'usuario': u, 'tipoPatron': t}
    return render(request, 'DesignCal/Patrones/editarPatrones.html', contexto)

def actualizarPatron(request):
    try:
        if request.method == "POST":
            t = TipoPatron.objects.get(pk = request.POST["tipoPatron"])
            u = Usuario.objects.get(pk = request.POST["usuario"])
            p = Patrone.objects.get(pk = request.POST["id"])
           
            if request.FILES:
                ruta_foto = str(BASE_DIR) + str(p.imagen.url)

                if path.exists(ruta_foto):
                    if p.imagen.url != "/uploads/DesignCal/fotos/default.jpg":
                        remove(ruta_foto)
                else:
                    raise Exception("La imagen no existe o no se encuentra")
                
                fss = FileSystemStorage()
                a = request.FILES["archivo"]
                archivo = fss.save("DesignCal/files/" + a.name, a)
                f = request.FILES["imagen"]
                file = fss.save("DesignCal/fotos/" + f.name, f)

                p.imagen = file
                p.archivo = archivo
            else:
                print("No se seleccionó foto nueva para éste patrón.")

            p.nombreArchivo = request.POST["nombreArchivo"]
            p.descripcion = request.POST["descripcion"]
            p.precio = request.POST["precio"]
            p.usuario = u
            p.tipoPatron = t

            p.save()
            messages.success(request, "Usuario actualizado con éxito")
            return redirect('DesignCal:patron')
        else:
            messages.warning(request, "No hay cambios")
            return redirect('DesignCal:patron')
    except Exception as e:
        messages.error(request, "Error: " + str(e))
        return redirect('DesignCal:patron')

def buscarPatron(request):
    if request.method == "POST":
        q = Patrone.objects.filter(Q(nombreArchivo__icontains = request.POST["dato"]) |
                                   Q(descripcion__icontains = request.POST["dato"]) |
                                   Q(precio__icontains = request.POST["dato"]) |
                                   Q(usuario__usuario__icontains = request.POST["dato"]) |
                                   Q(tipoPatron__icontains = request.POST["dato"]))
        pag = Paginator(q, 5)
        page_number = request.GET.get('page')
        q = pag.get_page(page_number)
        contexto = {'datos': q, 'datoBuscado': request.POST["dato"]}
        return render(request, 'DesignCal/Patrones/listarPatronesAjax.html', contexto)
    else:
        messages.warning(request, "Usted no envió datos...")

aplicativo/DesignCal/templates/DesignCal/Rol/crearRol.html
{% extends "DesignCal/base.html" %}

{% block body %}

<h1>Ingresar un nuevo rol</h1>

    <form action="{% url 'DesignCal:rol-guardar' %}" method="post">
        {% csrf_token %}
        <label for="NombreRol">Nombre del rol</label>
        <input class="form-control" type="text" name="NombreRol" id="NombreRol" placeholder="Nombre del rol" required>
        <br/><button class="btn btn-primary" type="submit">Agregar</button>
    </form>
{% endblock %}

aplicativo/DesignCal/templates/DesignCal/Rol/editarRol.html
{% extends "DesignCal/base.html" %}

{% block body %}

<h1>Editar Rol ( {{ datos.NombreRol }} )</h1>
<form action="{% url 'DesignCal:rol-actualizar' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{ datos.id }}">
    <label for="NombreRol">Nombre del rol</label>
    <input class="form-control" type="text" name="NombreRol" id="NombreRol" value="{{ datos.NombreRol }}" required>
    </select><br/>
    <br/><button class="btn btn-primary" type="submit">Editar</button>
</form>

{% endblock %}

aplicativo/DesignCal/templates/DesignCal/Rol/listarRoles.html
{% extends "DesignCal/base.html" %}

{% block body %}

  <h1 id="rol">Roles</h1>

    <div class="dat">
      <input class="form-control me-2" id="dato" type="search" placeholder="Buscar" aria-label="Search" name="dato" value="{{ datoBuscado }}" style=" width:10%;" onkeyup="buscar('{% url 'DesignCal:rol-buscar' %}');">
      {% csrf_token %}
    </div>

  <br />
  {% if datoBuscado %}
    <a href="{% url 'DesignCal:roles' %}">Volver</a>
  {% endif %}

  <div id="respuesta">
  {% if datos %}

    <nav aria-label="..." style="margin-left: 7%; display: grid; grid-template-columns: 50% 50%;">
      <ul class="pagination">
        <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
          <a class="page-link" {% if datos.has_previous %} href="?page={{ datos.previous_page_number }}" {% endif %}>Anterior</a>
        </li>

        {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
        <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
          <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endfor %}

        <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
          <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}" {% endif %}>Siguiente</a>
        </li>
      </ul>
      <div style="display: flex;
      flex-direction: row-reverse;margin-right: 14%;">
        <a class="btn btn-outline-success my-2 my-sm-0" style="height: 70%;" href="{% url 'DesignCal:rol-add' %}">Agregar Nuevo Rol</a>
      </div>
    </nav>

    <table class="table table-striped container my-3" id="list">
      <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th colspan="2">Acciones</th>
      </thead>
      <tbody>
        {% for r in datos %}
        <tr>
          <td>{{ r.id }}</td>
          <td>{{ r.NombreRol }}</td>
          <td><a class="btn btn-warning" href="{% url 'DesignCal:rol-editar' r.id %}">Editar</a></td>
          <td><a class="btn btn-danger" onclick="confirmar('{% url 'DesignCal:rol-eliminar' r.id %}')">Eliminar</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    Pág. {{ datos.number }} de {{ datos.paginator.num_pages }}.
    {% else %}
    <h1>No hay datos</h1>
    {% endif %}
  </div>

{% endblock %}

aplicativo/DesignCal/templates/DesignCal/Rol/listarRolesAjax.html
{% if datos %}

    <nav aria-label="..." style="margin-left: 7%; display: grid; grid-template-columns: 50% 50%;">
      <ul class="pagination">
        <li class="page-item {% if not datos.has_previous %}disabled{% endif %}">
          <a class="page-link" {% if datos.has_previous %} href="?page={{ datos.previous_page_number }}" {% endif %}>Anterior</a>
        </li>

        {% for i in "x"|rjust:datos.paginator.num_pages|make_list %}
        <li class="page-item {% if forloop.counter == datos.number %}active{% endif %}" aria-current="page">
          <a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endfor %}

        <li class="page-item {% if not datos.has_next %}disabled{% endif %}">
          <a class="page-link" {% if datos.has_next %}href="?page={{ datos.next_page_number }}" {% endif %}>Siguiente</a>
        </li>
      </ul>
      <div style="display: flex;
      flex-direction: row-reverse;margin-right: 14%;">
        <a class="btn btn-outline-success my-2 my-sm-0" style="height: 70%;" href="{% url 'DesignCal:rol-add' %}">Agregar Nuevo Rol</a>
      </div>
    </nav>

    <table class="table table-striped container my-3" id="list">
      <thead>
        <th>ID</th>
        <th>Nombre</th>
        <th colspan="2" style="text-align: end;">Acciones</th>
      </thead>
      <tbody>
        {% for r in datos %}
        <tr>
          <td>{{ r.id }}</td>
          <td>{{ r.NombreRol }}</td>
          <td>
            <td><a class="btn btn-warning" href="{% url 'DesignCal:rol-editar' r.id %}">Editar</a></td>
            </td>
            <td><a class="btn btn-danger" onclick="confirmar('{% url 'DesignCal:rol-eliminar' r.id %}')">Eliminar</a></td>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    Pág. {{ datos.number }} de {{ datos.paginator.num_pages }}.
    {% else %}
    <h1>No hay datos</h1>
    {% endif %}
  </div>